### ISSUE TITLE
Ongoing Task List

### ISSUE THREAD

**Issue by Deamon5550** [Deamon5550/VisualScripting#1]
- [ ] Refine unit tests
- [ ] Add node packages
- [ ] Add security manager to restrict node packages
- [ ] Add timeouts to runtime
- [ ] Add generic serialization base
- [ ] Add text serializer
- [ ] Add bytecode serializer
- [ ] Add do/while/switch/if-else/sequence control flow nodes
- [ ] Add support for 'functions'
- [ ] Expand basic math nodes (trig/bit-shift/sign)
